permalink: /:year/:month/:day/:title/

# 站点设置
title: "Heng"
email: lihengszh@aliyun.com
description: "李恒的个人博客"
keywords: ""

# 阅读处理
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 用户信息设置
github_username: liheng

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: ""
url: "http://henggeneral.github.io/"
#url: "http://127.0.0.1:4000"

# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed
